
datasource:
  master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/investment?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: user_investment
    password: user_investment_pw
    validation-query: select 1
    test-on-borrow: true
    test-while-idle: true
    validation-query-timeout: 3
    default-auto-commit: true
    pool-prepared-statements: true
    initial-size: 10
    max-total: 20
    max-idle: 10
    min-idle: 10
    max-wait-millis: 3000
    min-evictable-idle-time-millis: 55000
    time-between-eviction-runs-millis: 10000
    num-tests-per-eviction-run: 5

  slave:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23306/investment?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: user_investment
    password: user_investment_pw
    validation-query: select 1
    test-on-borrow: true
    test-while-idle: true
    validation-query-timeout: 3
    default-auto-commit: true
    pool-prepared-statements: true
    initial-size: 10
    max-total: 80
    max-idle: 80
    min-idle: 10
    max-wait-millis: 3000
    min-evictable-idle-time-millis: 55000
    time-between-eviction-runs-millis: 5000
    num-tests-per-eviction-run: 8
